# Availabe config variables and default values
#
# The config flags are designed to be overriden from the app
# makefile, not editted here.

CONFIG_ENABLE_WATCHPOINTS ?= 1

CONFIG_ENABLE_TARGET_SIDE_DEBUG_MODE ?= 1

CONFIG_PASSIVE_BREAKPOINT_IMPL ?= c

CONFIG_PULL_DOWN_ON_CODEPOINT_LINES ?= 0

LIBEDB_ENABLE_UART ?= 1
